IF NOT EXISTS(SELECT * FROM sys.databases WHERE sys.databases.name = 'Shelf')
BEGIN
CREATE DATABASE Shelf
END

USE SHELF

CREATE TABLE Perfil
(
IDPerfil BIGINT IDENTITY(1,1) PRIMARY KEY,
Nome VARCHAR(80) NOT NULL UNIQUE,
Atendimento SMALLINT NOT NULL,
Perfil TINYINT NOT NULL,
Setor TINYINT NOT NULL,
Funcionario TINYINT NOT NULL,
Manutencao TINYINT NOT NULL,
Cliente TINYINT NOT NULL,
)

CREATE TABLE Setor
(
IDSetor BIGINT IDENTITY(1,1) PRIMARY KEY,
Nome VARCHAR(80) NOT NULL UNIQUE
)

CREATE TABLE Funcionario
(
IDFuncionario BIGINT IDENTITY(1,1) PRIMARY KEY,
Setor_ID BIGINT NOT NULL FOREIGN KEY 
REFERENCES Setor(IDSetor),
Perfil_ID BIGINT NOT NULL FOREIGN KEY
REFERENCES Perfil(IDPerfil),
Nome VARCHAR(80) UNIQUE NOT NULL,
Senha VARCHAR(80) NOT NULL
)