CREATE DATABASE SHELF
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [SHELF].[dbo].[AntiVirus](
	[IDAntiVirus] [bigint] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](80) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDAntiVirus] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [SHELF].[dbo].[Aplicativo](
	[IDAplicativo] [bigint] IDENTITY(1,1) NOT NULL,
	[Descricao] [varchar](80) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IDAplicativo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Descricao] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [SHELF].[dbo].[Categoria](
	[IDCategoria] [bigint] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](80) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IDCategoria] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Nome] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [SHELF].[dbo].[Rede](
	[IDRede] [bigint] IDENTITY(1,1) NOT NULL,
	[Codigo] [bigint] NULL,
	[Nome] [varchar](80) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDRede] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [SHELF].[dbo].[Cliente](
	[IDCliente] [bigint] IDENTITY(1,1) NOT NULL,
	[Rede_ID] [bigint] NULL,
	[Codigo] [bigint] NULL,
	[RazaoSocial] [varchar](80) NULL,
	[NomeFantasia] [varchar](80) NULL,
	[CPFCNPJ] [varchar](18) NULL,
	[InscricaoEstadual] [varchar](20) NULL,
	[Email] [varchar](80) NULL,
	[CEP] [varchar](9) NULL,
	[Endereco] [varchar](80) NULL,
	[Bairro] [varchar](80) NULL,
	[Numero] [varchar](5) NULL,
	[Cidade] [varchar](50) NULL,
	[Estado] [varchar](30) NULL,
 CONSTRAINT [PK__Cliente__9B8553FC03317E3D] PRIMARY KEY CLUSTERED 
(
	[IDCliente] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [SHELF].[dbo].[Cliente]  WITH CHECK ADD  CONSTRAINT [FK__Cliente__Rede_ID__0519C6AF] FOREIGN KEY([Rede_ID])
REFERENCES [SHELF].[dbo].[Rede] ([IDRede])
GO

ALTER TABLE [SHELF].[dbo].[Cliente] CHECK CONSTRAINT [FK__Cliente__Rede_ID__0519C6AF]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SHELF].[dbo].[FuncionarioDadosPessoais](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[Nome] [nchar](50) NULL,
	[RG] [nchar](15) NULL,
	[CPF] [nchar](15) NULL,
	[Telefone] [nchar](15) NULL,
	[PIS] [nchar](15) NULL,
	[Email] [nchar](80) NULL,
	[CEP] [nchar](9) NULL,
	[Endereco] [nchar](80) NULL,
	[Bairro] [nchar](80) NULL,
	[Numero] [nchar](5) NULL,
	[Cidade] [nchar](50) NULL,
	[Estado] [nchar](30) NULL,
 CONSTRAINT [PK_FuncionarioDadosPessoais] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [SHELF].[dbo].[Contrato](
	[IDContrato] [bigint] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](80) NULL,
	[Ativo] [bit] NULL,
	[Cliente_ID] [bigint] NOT NULL,
 CONSTRAINT [PK__Contrato__B71357DE0CBAE877] PRIMARY KEY CLUSTERED 
(
	[IDContrato] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [SHELF].[dbo].[Contrato]  WITH CHECK ADD  CONSTRAINT [FK__Contrato__Client__0EA330E9] FOREIGN KEY([Cliente_ID])
REFERENCES [SHELF].[dbo].[Cliente] ([IDCliente])
GO

ALTER TABLE [SHELF].[dbo].[Contrato] CHECK CONSTRAINT [FK__Contrato__Client__0EA330E9]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [SHELF].[dbo].[MSWindows](
	[IDWindows] [bigint] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](80) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDWindows] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SHELF].[dbo].[Protocolo](
	[IDProtocolo] [bigint] IDENTITY(1,1) NOT NULL,
	[Protocolo] [bigint] NULL,
	[Tipo] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[IDProtocolo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SHELF].[dbo].[ProtocoloExtension](
	[Protocolo] [int] NOT NULL,
	[Data] [datetime] NOT NULL
) ON [PRIMARY]

GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [SHELF].[dbo].[Setor](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](80) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Nome] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [SHELF].[dbo].[SubCategoria](
	[IDSubCategoria] [bigint] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](80) NOT NULL,
	[Categoria_ID] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IDSubCategoria] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [SHELF].[dbo].[SubCategoria]  WITH CHECK ADD FOREIGN KEY([Categoria_ID])
REFERENCES [SHELF].[dbo].[Categoria] ([IDCategoria])
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [SHELF].[dbo].[Telefone](
	[IDTelefone] [bigint] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](80) NULL,
	[Numero] [varchar](14) NULL,
	[Cargo] [varchar](80) NULL,
	[Cliente_ID] [bigint] NULL,
 CONSTRAINT [PK__Telefone__5B9BDE2107F6335A] PRIMARY KEY CLUSTERED 
(
	[IDTelefone] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [SHELF].[dbo].[Telefone]  WITH CHECK ADD  CONSTRAINT [FK__Telefone__Client__09DE7BCC] FOREIGN KEY([Cliente_ID])
REFERENCES [SHELF].[dbo].[Cliente] ([IDCliente])
GO

ALTER TABLE [SHELF].[dbo].[Telefone] CHECK CONSTRAINT [FK__Telefone__Client__09DE7BCC]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [SHELF].[dbo].[Versao](
	[IDVersao] [bigint] IDENTITY(1,1) NOT NULL,
	[Aplicativo_ID] [bigint] NULL,
	[Versao] [varchar](11) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDVersao] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [SHELF].[dbo].[Versao]  WITH CHECK ADD FOREIGN KEY([Aplicativo_ID])
REFERENCES [SHELF].[dbo].[Aplicativo] ([IDAplicativo])
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [SHELF].[dbo].[Perfil](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](80) NOT NULL,
	[Atendimento] [smallint] NOT NULL,
	[Manutencao] [smallint] NOT NULL,
	[Funcionario] [smallint] NULL,
	[Cliente] [smallint] NOT NULL,
	[ID_Setor] [bigint] NOT NULL,
 CONSTRAINT [PK__Perfil__9C0757B52C3393D0] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UQ__Perfil__7D8FE3B22F10007B] UNIQUE NONCLUSTERED 
(
	[Nome] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [SHELF].[dbo].[Perfil]  WITH CHECK ADD  CONSTRAINT [FK_Perfil_Setor] FOREIGN KEY([ID_Setor])
REFERENCES [SHELF].[dbo].[Setor] ([ID])
GO

ALTER TABLE [SHELF].[dbo].[Perfil] CHECK CONSTRAINT [FK_Perfil_Setor]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [SHELF].[dbo].[Computador](
	[IDComputador] [bigint] IDENTITY(1,1) NOT NULL,
	[Cliente_ID] [bigint] NULL,
	[Nome] [varchar](40) NULL,
	[MSWindows_ID] [bigint] NULL,
	[LicencaWindows] [varchar](29) NULL,
	[AntiVirus_ID] [bigint] NULL,
	[LicencaAntiVirus] [varchar](29) NULL,
	[MacAddress] [varchar](17) NULL,
	[DataAquisicaoAntiVirus] [datetime] NULL,
	[DataTerminoAntiVirus] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IDComputador] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [SHELF].[dbo].[Computador]  WITH CHECK ADD FOREIGN KEY([AntiVirus_ID])
REFERENCES [SHELF].[dbo].[AntiVirus] ([IDAntiVirus])
GO

ALTER TABLE [SHELF].[dbo].[Computador]  WITH CHECK ADD  CONSTRAINT [FK__Computado__Clien__1B0907CE] FOREIGN KEY([Cliente_ID])
REFERENCES [SHELF].[dbo].[Cliente] ([IDCliente])
GO

ALTER TABLE [SHELF].[dbo].[Computador] CHECK CONSTRAINT [FK__Computado__Clien__1B0907CE]
GO

ALTER TABLE [SHELF].[dbo].[Computador]  WITH CHECK ADD FOREIGN KEY([MSWindows_ID])
REFERENCES [SHELF].[dbo].[MSWindows] ([IDWindows])
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [SHELF].[dbo].[Item](
	[IDItem] [bigint] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](80) NOT NULL,
	[SubCategoria_ID] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IDItem] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [SHELF].[dbo].[Item]  WITH CHECK ADD FOREIGN KEY([SubCategoria_ID])
REFERENCES [SHELF].[dbo].[SubCategoria] ([IDSubCategoria])
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [SHELF].[dbo].[Atendimento](
	[IDAtendimento] [bigint] IDENTITY(1,1) NOT NULL,
	[Problema] [varchar](255) NULL,
	[Protocolo_ID] [bigint] NULL,
	[Cliente_ID] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IDAtendimento] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [SHELF].[dbo].[Atendimento]  WITH CHECK ADD FOREIGN KEY([Cliente_ID])
REFERENCES [SHELF].[dbo].[Cliente] ([IDCliente])
GO

ALTER TABLE [SHELF].[dbo].[Atendimento]  WITH CHECK ADD FOREIGN KEY([Protocolo_ID])
REFERENCES [SHELF].[dbo].[Protocolo] ([IDProtocolo])
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SHELF].[dbo].[Problema](
	[IDProblema] [bigint] IDENTITY(1,1) NOT NULL,
	[Categoria_ID] [bigint] NOT NULL,
	[SubCategoria_ID] [bigint] NOT NULL,
	[Item_ID] [bigint] NOT NULL,
	[Aplicativo_ID] [bigint] NOT NULL,
	[Versao_ID] [bigint] NOT NULL,
	[Atendimento_ID] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IDProblema] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [SHELF].[dbo].[Problema]  WITH CHECK ADD FOREIGN KEY([Aplicativo_ID])
REFERENCES [SHELF].[dbo].[Aplicativo] ([IDAplicativo])
GO

ALTER TABLE [SHELF].[dbo].[Problema]  WITH CHECK ADD FOREIGN KEY([Atendimento_ID])
REFERENCES [SHELF].[dbo].[Atendimento] ([IDAtendimento])
GO

ALTER TABLE [SHELF].[dbo].[Problema]  WITH CHECK ADD FOREIGN KEY([Categoria_ID])
REFERENCES [SHELF].[dbo].[Categoria] ([IDCategoria])
GO

ALTER TABLE [SHELF].[dbo].[Problema]  WITH CHECK ADD FOREIGN KEY([Item_ID])
REFERENCES [SHELF].[dbo].[Item] ([IDItem])
GO

ALTER TABLE [SHELF].[dbo].[Problema]  WITH CHECK ADD FOREIGN KEY([SubCategoria_ID])
REFERENCES [SHELF].[dbo].[SubCategoria] ([IDSubCategoria])
GO

ALTER TABLE [SHELF].[dbo].[Problema]  WITH CHECK ADD FOREIGN KEY([Versao_ID])
REFERENCES [SHELF].[dbo].[Versao] ([IDVersao])
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [SHELF].[dbo].[FuncionarioLogin](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_Perfil] [bigint] NOT NULL,
	[Nome] [varchar](80) NOT NULL,
	[Senha] [varchar](80) NOT NULL,
	[ID_FuncionarioDados] [bigint] NOT NULL,
 CONSTRAINT [PK__Funciona__3214EC27403A8C7D] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UQ__Funciona__7D8FE3B24316F928] UNIQUE NONCLUSTERED 
(
	[Nome] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [SHELF].[dbo].[FuncionarioLogin]  WITH CHECK ADD FOREIGN KEY([ID_FuncionarioDados])
REFERENCES [SHELF].[dbo].[FuncionarioDadosPessoais] ([ID])
GO

ALTER TABLE [SHELF].[dbo].[FuncionarioLogin]  WITH CHECK ADD  CONSTRAINT [FK__Funcionar__Perfi__3F466844] FOREIGN KEY([ID_Perfil])
REFERENCES [SHELF].[dbo].[Perfil] ([ID])
GO

ALTER TABLE [SHELF].[dbo].[FuncionarioLogin] CHECK CONSTRAINT [FK__Funcionar__Perfi__3F466844]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [SHELF].[dbo].[AtendimentoDetalhado](
	[IDAtendimentoDetalhado] [bigint] IDENTITY(1,1) NOT NULL,
	[Atendimento_ID] [bigint] NOT NULL,
	[StatusAtendimento] [bigint] NOT NULL,
	[Funcionario_ID] [bigint] NOT NULL,
	[DataInicio] [datetime] NULL,
	[DataFinal] [datetime] NULL,
	[Solucao] [varchar](255) NULL,
	[Contato] [varchar](80) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDAtendimentoDetalhado] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [SHELF].[dbo].[AtendimentoDetalhado]  WITH CHECK ADD FOREIGN KEY([Atendimento_ID])
REFERENCES [SHELF].[dbo].[Atendimento] ([IDAtendimento])
GO

ALTER TABLE [SHELF].[dbo].[AtendimentoDetalhado]  WITH CHECK ADD  CONSTRAINT [FK__Atendimen__Funci__5165187F] FOREIGN KEY([Funcionario_ID])
REFERENCES [SHELF].[dbo].[FuncionarioLogin] ([ID])
GO

ALTER TABLE [SHELF].[dbo].[AtendimentoDetalhado] CHECK CONSTRAINT [FK__Atendimen__Funci__5165187F]
GO

